### ISSUE TITLE
파일 및 디렉토리 규칙

### ISSUE THREAD

**Issue by seonghun-dev** [TinyML-Team/TinyML#1]
**파일 및 디렉토리 규칙**

DeepLearning Model은 deeplearning
BLE Module은 bloothmodule
을 뒤에 붙여서 표현해주시길 바랍니다.

**Comment by MinjuKim0217** [comment]
> **파일 및 디렉토리 규칙**
> 
> DeepLearning Model은 deeplearning
> BLE Module은 bloothmodule
> 을 뒤에 붙여서 표현해주시길 바랍니다.
